config/routes.rb
Rails.application.routes.draw do
  root "page#index"

  get '/about' => 'page#about', as: 'about'

  resources :admin, :path => "admin", only: [:index, :new, :create]
  	post '/session' => 'admin#auth', as: "session"
  	get '/signout' => 'admin#signout', as: "admin_signout"
		get '/admin/images' => "admin#images", as: "images_admin"
		get '/admin/articles' => "admin#articles", as: "articles_admin"
		get '/admin/edit/:id' => "admin#edit", as: "edit_admin"
		patch '/admin/update' => 'admin#update', as: 'update_admin'

	resources :gallery, :path => "gallery"
		get '/admin/add-image' => "gallery#new", as: "add_gallery"
		post '/admin/create-image' => "gallery#create", as: "create_gallery"

	resources :article, :path => "article"
		get '/article/:id' => "article#show", as: "show_article"

end

app/views/admin/_admin_nav.html.slim
.container
	.admin-nav.darkgrey
		ul.nav.nav-pills
			li
				= link_to "Manage Articles", articles_admin_path
			li
				= link_to "Create Article", new_admin_path
			li
				= link_to "Manage Images", images_admin_path
			li
				= link_to "Add Image", add_gallery_path

app/views/admin/articles.html.slim
- provide(:title, 'technimg :: Admin - Manage Articles')
.container
	= render partial: 'admin_nav' 
	- unless flash[:notice].blank?
		.alert.alert-success
			= flash[:notice]

	h1 Manage Articles
	= will_paginate @articles, renderer: BootstrapPagination::Rails
	table.table.table-striped
		thead
			tr
				th #
				th Title
				th Body Preview
				th
				th
				th
		tbody
			- @articles.each do |article|
				tr
					td 
						= article.id
					td 
						= article.title
					td
						= truncate(strip_tags(article.body), length: 150, omission: '...')
					td
						= link_to "View Article", show_article_path(article), class: "btn btn-primary", target:"blank"
					td
						= link_to "Edit Article", edit_admin_path(article.id), class: "btn btn-warning"
					td style="text-align: center"
						- case article.status
							- when 1
								.btn.btn-success.default-cursor Live
							- when 2
								.btn.btn-warning.default-cursor Preview
							- when 0 
								.btn.btn-danger.default-cursor Un-Published

					

app/views/admin/edit.html.slim
.container
	= render partial: "admin_nav"
	- unless flash[:notice].blank?
		.alert.alert-danger
			= flash[:notice]
	h1 Edit Article
	= form_for(@article, url: update_admin_path) do |f|
		= f.hidden_field :id
		= f.hidden_field :user_id, value: current_user.id
		= f.label :title
		= f.text_field :title, class: "form-control"
		br
		= f.label "Associate an Image (Insert ID #)"
		= f.text_field :gallery_id, class: "form-control"
		= f.check_box :exifshow
		| &nbsp;
		= f.label "Show Exif Data"
		.admin-image-preview
			= image_tag @article.gallery.try(:attachment_url)
		br
		= f.label :address
		= f.text_field :address, class: "form-control"
		br
		= f.cktext_area :body, class: 'ckeditor'
		br
		br
		= f.label :status
		br
		.input-group.radio
			= f.radio_button :status, 1
			= f.label "Published"
		.input-group.radio
			= f.radio_button :status, 2
			= f.label "Preview"
		input-group.radio
			= f.radio_button :status, 0
			= f.label "Un-Published"
		= f.submit "Submit", class: "btn-lg btn-primary"
		br

app/views/admin/images.html.slim
- provide(:title, 'technimg :: Manage Images')
.container
	= render partial: 'admin_nav'
	- unless flash[:notice].blank?
		.alert.alert-success
			= flash[:notice]
	h1 Manage Images
	table.table.table-striped
		thead
			tr
				th #
				th Preview
				th Name
				th Source
				th Delete
		tbody
			= will_paginate @images, params: {controller: :admin, action: :images}, renderer: BootstrapPagination::Rails
			- @images.each do |image|
				tr
					td 
						= image.id
					td 
						= image_tag image.attachment_url, class: "image-preview"
					td
						= image.name
					td
						= text_field_tag 'url', image.attachment_url, class: "form-control", readonly: true
					td
						= button_to "Delete", image, method: :delete, class: "btn btn-danger", confirm: "Are you sure you want to delete #{image.name}?"

app/views/admin/index.html.slim
- provide(:title, 'technimg :: Admin')
.container
	h1 Login
	= form_for(:admin, url: session_path) do |f|
		= f.label :name
		= f.text_field :name, class:"form-control"
		br
		= f.label :password
		= f.password_field :password ,class:"form-control"
		br
		= f.submit "Login", class: "btn btn-primary btn-large"

app/views/admin/new.html.slim
- provide(:title, 'technimg :: Create Article')
.container
	= render partial: 'admin_nav'
	h1 Create New Article
	= form_for(@article, url: admin_index_path) do |f|
		= f.hidden_field :user_id, value: current_user.id
		= f.label :title
		= f.text_field :title, class: "form-control"
		br
		= f.label "Associate an Image (Insert ID #)"
		= f.text_field :gallery_id, class: "form-control"
		= f.check_box :exifshow
		| &nbsp;
		= f.label "Show Exif Data"
		br
		= f.label :address
		= f.text_field :address, class: "form-control"
		br
		= f.cktext_area :body, class: 'ckeditor'
		br
		br
		= f.label :status
		br
		.input-group.radio
			= f.radio_button :status, 1
			= f.label "Published"
		.input-group.radio
			= f.radio_button :status, 2
			= f.label "Preview"
		input-group.radio
			= f.radio_button :status, 0
			= f.label "Un-Published"
		= f.submit "Submit", class: "btn-lg btn-primary"
		br