config/routes.rb
Rails.application.routes.draw do
  root "page#index"

  get '/about' => 'page#about', as: 'about'

  resources :admin, :path => "admin", only: [:index, :new, :create]
  	post '/session' => 'admin#auth', as: "session"
  	get '/signout' => 'admin#signout', as: "admin_signout"
		get '/admin/images' => "admin#images", as: "images_admin"
		get '/admin/articles' => "admin#articles", as: "articles_admin"
		get '/admin/edit/:id' => "admin#edit", as: "edit_admin"
		patch '/admin/update' => 'admin#update', as: 'update_admin'

	resources :gallery, :path => "gallery"
		get '/admin/add-image' => "gallery#new", as: "add_gallery"
		post '/admin/create-image' => "gallery#create", as: "create_gallery"

	resources :article, :path => "article"
		get '/article/:id' => "article#show", as: "show_article"

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :text
#  address    :string(255)
#  body       :text
#  user_id    :integer
#  status     :integer
#  created_at :datetime
#  updated_at :datetime
#  image      :text
#

class Article < ActiveRecord::Base
	belongs_to :gallery
	belongs_to :user

	def to_param
		filter_address = address.gsub(/[\s]+/,"-").gsub(/[^\w-]+/, "")
		"#{id}-#{filter_address}"
	end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
	def index
		if signed_in?
			@articles = Article.paginate(page: params[:page], per_page: 10).order("id DESC")
		else 
			@articles = Article.paginate(page: params[:page], per_page: 10).where(status: 1).order("id DESC")
		end
	end

	def show
		@article = Article.find(params[:id])
		@prev_article = Article.find_by_id(@article.id - 1)
		@next_article = Article.find_by_id(@article.id + 1) 
		if File.exist?('public'+@article.gallery.attachment_url)
			@exif = EXIFR::JPEG.new('public'+@article.gallery.attachment_url).to_hash
			process_exif(@exif)
		end
		if @article.status == 1 || @article.status == 2 || signed_in?
			render 'show'
		else
			redirect_to article_index_path
		end
	end

	private
		def process_exif(exif_data)
			exif_data.delete(:orientation)
			exif_data.delete(:photometric_interpretation)
			exif_data.delete(:comment)
			exif_data.delete(:exposure_program)
			exif_data.delete(:bits)
			exif_data.delete(:image_width)
			exif_data.delete(:image_length)
			exif_data.delete(:bits_per_sample)
			exif_data.delete(:make)
			exif_data.delete(:width)
			exif_data.delete(:height)
			exif_data.delete(:x_resolution)
			exif_data.delete(:y_resolution)
			exif_data.delete(:resolution_unit)
			exif_data.delete(:ycb_cr_positioning)
			exif_data.delete(:subject_area)
			exif_data.delete(:subsec_time_original)
			exif_data.delete(:subsec_time_digitized)
			exif_data.delete(:color_space)
			exif_data.delete(:pixel_x_dimension)
			exif_data.delete(:pixel_y_dimension)
			exif_data.delete(:sensing_method)
			exif_data.delete(:white_balance)
			exif_data.delete(:scene_capture_type)
			exif_data.delete(:gps_latitude_ref)
			exif_data.delete(:gps_latitude)
			exif_data.delete(:gps_longitude_ref)
			exif_data.delete(:gps_longitude)
			exif_data.delete(:gps_altitude)
			exif_data.delete(:gps_time_stamp)
			exif_data.delete(:gps_dop)
			exif_data.delete(:gps_date_stamp)
			exif_data.delete(:date_time)
			exif_data.delete(:date_time_original)
			exif_data.delete(:date_time_digitized)
			exif_data.delete(:gps_date_stamp)
			exif_data.delete(:gps_date_stamp)


			exif_data[:exposure_time] = exif_data[:exposure_time].to_i if exif_data[:exposure_time].present?

			exif_data[:f_number] = exif_data[:f_number].to_i if exif_data[:f_number].present?
		end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/article/index.html.slim
- provide(:title, 'technimg :: Articles')
.container-fluid#articles
	.hero
		.welcome

.container#articles
	- @articles.each do |article|
		article
			.title
				= link_to show_article_path(article) do
					h2 #{article.title}
			- if article.status == 2
				.alert.alert-warning 
					strong This article is in preview mode
			-elsif article.status == 0
				.alert.alert-danger
					strong This article is unpublished
					
			= link_to show_article_path(article) do
				.image-preview style="background-image: url(#{article.gallery.try(:attachment_url)})"
			.preview
				= Nokogiri::HTML.parse(article.body).css('p').first.to_s.html_safe
			.read-more
				= link_to "Read More", show_article_path(article)				
	= will_paginate @articles, previous_label: "< Newer Posts", next_label: "Older Posts >", renderer: BootstrapPagination::Rails

app/views/article/show.html.slim
- provide(:title, "technimg :: Article :: #{@article.title}")
.container-fluid#article
	.target
		.hero style="background-image: url(#{@article.gallery.try(:attachment_url)})"

.container.article#article 
	.featured-image
		= image_tag @article.gallery.attachment_url
	.breadcrumbs
		= link_to "<< Return to Articles", article_index_path
	- if @article.status == 2
		.alert.alert-warning 
			strong This article is in preview mode
	-elsif @article.status == 0
		.alert.alert-danger
			strong This article is unpublished
	article
		h1
			= @article.title
		h5
			| Posted by 
			= @article.user.name
			|  on 
			= @article.updated_at.in_time_zone("Pacific Time (US & Canada)").strftime('%h %d, %Y @ %l:%M %p')
		- if @article.exifshow
			.exif-data
				#toggle-exif-data Toggle Photo Information
				#exif
					table.table-striped
						- if @exif.present?
							-@exif.each do |k,v|
								tr
									td #{k.to_s.gsub(/[_]+/," ").split(' ').map {|w| w.capitalize }.join(' ')}
									td #{v}
		= @article.body.html_safe

	.more-links
		- if @next_article
			= link_to article_path(@next_article) do
				.btn.btn-info.pull-left 
					| << 
					=@next_article.title

		- if @prev_article
			= link_to article_path(@prev_article) do
				.btn.btn-info.pull-right 
					=@prev_article.title
					|  >>

	= link_to article_index_path, class: "return-to-article" do
		.btn.btn-info.custom-center Return to Articles