config/routes.rb
Rails.application.routes.draw do
  root "page#index"

  get '/about' => 'page#about', as: 'about'

  resources :admin, :path => "admin", only: [:index, :new, :create]
  	post '/session' => 'admin#auth', as: "session"
  	get '/signout' => 'admin#signout', as: "admin_signout"
		get '/admin/images' => "admin#images", as: "images_admin"
		get '/admin/articles' => "admin#articles", as: "articles_admin"
		get '/admin/edit/:id' => "admin#edit", as: "edit_admin"
		patch '/admin/update' => 'admin#update', as: 'update_admin'

	resources :gallery, :path => "gallery"
		get '/admin/add-image' => "gallery#new", as: "add_gallery"
		post '/admin/create-image' => "gallery#create", as: "create_gallery"

	resources :article, :path => "article"
		get '/article/:id' => "article#show", as: "show_article"

end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id         :integer          not null, primary key
#  name       :text
#  created_at :datetime
#  updated_at :datetime
#  attachment :text
#

class Gallery < ActiveRecord::Base
	mount_uploader :attachment, ImageUploader
	validates :name, presence: true
	validates :attachment, presence: true

	has_many :articles
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
	def new 
		@image = Gallery.new
	end

	def create
		@image = Gallery.new(gallery_params)
		if @image.save
			redirect_to images_admin_path, notice: "Image #{@image.name} uploaded successfully"
		else 
			redirect_to new_gallery_path, notice: "ERROR UPLOADING FILES"
		end
	end

	def destroy
		@image = Gallery.find(params[:id])
		@image.destroy
		redirect_to images_admin_path, notice: "#{@image.name} was deleted"
	end

	private
		def gallery_params
			params.require(:gallery).permit(:name, :attachment)
		end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/index.html.slim
-params[:controller] = 'admin'
.container
	= render partial: 'admin/admin_nav'
	- unless flash[:notice].blank?
		.alert.alert-success
			= flash[:notice]
	h1 Manage Images
	table.table.table-striped
		thead
			tr
				th #
				th Preview
				th Name
				th Source
				th Delete
		tbody
			- @images.each do |image|
				tr
					td 
						= image.id
					td 
						= image_tag image.attachment_url, class: "image-preview"
					td
						= image.name
					td
						= image.attachment_url
					td
						= button_to "Delete", image, method: :delete, class: "btn btn-danger", confirm: "Are you sure you want to delete #{image.name}?"

app/views/gallery/new.html.slim
- provide(:title, 'technimg :: Add Image')
-params[:controller] = 'admin'
.container
	= render partial: 'admin/admin_nav'
	- unless flash[:notice].blank?
		.alert.alert-danger
			= flash[:notice]
	h1 Add New Image
	= form_for(@image, html: { multipart: true }, url: create_gallery_path) do |f|
		= f.label :name
		= f.text_field :name, class: "form-control"
		br
		= f.label :attachment
		= f.file_field :attachment, class: "form-control"
		br
		= f.submit "Submit", class: "btn-lg btn-primary"
		br