config/routes.rb
Rails.application.routes.draw do
  root "page#index"

  get '/about' => 'page#about', as: 'about'

  resources :admin, :path => "admin", only: [:index, :new, :create]
  	post '/session' => 'admin#auth', as: "session"
  	get '/signout' => 'admin#signout', as: "admin_signout"
		get '/admin/images' => "admin#images", as: "images_admin"
		get '/admin/articles' => "admin#articles", as: "articles_admin"
		get '/admin/edit/:id' => "admin#edit", as: "edit_admin"
		patch '/admin/update' => 'admin#update', as: 'update_admin'

	resources :gallery, :path => "gallery"
		get '/admin/add-image' => "gallery#new", as: "add_gallery"
		post '/admin/create-image' => "gallery#create", as: "create_gallery"

	resources :article, :path => "article"
		get '/article/:id' => "article#show", as: "show_article"

end

app/views/layouts/_footer.html.slim
footer.navbar.navbar-inverse
	p 
		

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-inverse

	.navbar-header
		button.navbar-toggle type="button" data-toggle="collapse" data-target="#main-navbar-collapse"
			span.sr-only Toggle Nav
			span.icon-bar
			span.icon-bar
			span.icon-bar
		= link_to root_path, class: "navbar-brand" do
			= image_tag "logos/technimg_logo_white_sm.png", {id: "header_logo"}

	.collapse.navbar-collapse#main-navbar-collapse
		ul.nav.navbar-nav.pull-right
			li
				=link_to "Home", root_path
			li 
				= link_to "About", about_path
			li
				= link_to "Articles", article_index_path
			- if signed_in?
				li.dropdown 
					= link_to "#", class: "dropdown-toggle", data: { toggle: "dropdown" } do
						| Admin Tools 
						span.caret
					ul.dropdown-menu
						li
							= link_to "Admin Home", admin_index_path
						li
							= link_to "Log Out Admin", admin_signout_path

app/views/layouts/application.html.slim
doctype html
html
	head
		title 
			= yield(:title)
		= custom_meta(@article).html_safe if @article.present? && params[:controller] != 'admin'
		= default_meta.html_safe unless @article.present?
		meta name="viewport" content="width=device-width, initial-scale=1"
		= stylesheet_link_tag 'application', media: 'all'
		= stylesheet_link_tag params[:controller] if Technimg::Application.assets.find_asset("#{params[:controller]}.css")
		= javascript_include_tag 'application'
		= render partial: 'shared/google_analytics'
  	= csrf_meta_tags
	body
		= render partial: 'layouts/navbar'
		= yield
		= render partial: 'layouts/footer'